name: Build on Ubuntu 22.04
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt update
    - run: sudo apt install meson ninja-build imagemagick jhead
    - run: meson build
    - run: meson compile -C build
