name: Build on Linux
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  fedora:
    runs-on: ubuntu-latest
    container: "registry.fedoraproject.org/fedora:rawhide"
    steps:
      - name: Install prerequisites
        run: |
          dnf install --assumeyes \
            gcc \
            git \
            meson \
            ImageMagick \
            jhead
      - uses: actions/checkout@v3
      - name: Build Budgie Backgrounds
        run: |
          meson build
          meson compile -C build
